postgresql:
  enabled: false # ביטלנו את ה-DB של ה-Chart

externalDB:
  enabled: true
  type: postgres
  host: postgres-db-svc.mattermost.svc.cluster.local # הכתובת של ה-Service שיצרנו
  port: 5432
  user: mmuser
  password: password123
  database: mattermost
