# ביטול מסד נתונים חיצוני
externalDB:
  enabled: false

# הגדרת PostgreSQL פנימי - שים לב למבנה השדות!
postgresql:
  enabled: true
  auth:
    database: mattermost
    username: mmuser
    password: password123
  persistence:
    enabled: false  # ביטול אחסון לטובת המהירות ב-Minikube

# הגדרות המטרמוסט
config:
  SiteURL: "http://localhost:8065"

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: mattermost.local
      paths:
        - path: /
