postgresql:
  enabled: false # אנחנו משתמשים בפוד העצמאי שהקמנו

externalDB:
  enabled: true
  type: postgres
  # השם של ה-Service שיצרנו קודם (או ניצור עכשיו)
  host: postgres-db-svc.mattermost.svc.cluster.local 
  port: 5432
  user: mmuser
  password: password123
  database: mattermost
